<?php declare(strict_types = 1);

/**
 * This file is part of the FireHub Web Application Framework package
 *
 * @author Danijel Galić <danijel.galic@outlook.com>
 * @copyright 2025 FireHub Web Application Framework
 * @license <https://opensource.org/licenses/OSL-3.0> OSL Open Source License version 3
 *
 * @php-version 8.4
 * @package Core\Support
 *
 * @version GIT: $Id$ Blob checksum.
 */

namespace FireHub\Core\Support\LowLevel;

use FireHub\Core\Support\Exceptions\RandomException;
use FireHub\Core\Support\Exceptions\Random\ {
    MaxLessThenMinException, NumberGreaterThenMaxException, NumberLessThenMinException
};
use Random\RandomException as InternalRandomException;

use function mt_getrandmax;
use function mt_rand;
use function random_bytes;
use function random_int;

/**
 * ### Random generated value low-level proxy class
 * @since 1.0.0
 */
final class Random {

    /**
     * ### Generate a random value via the Mersenne Twister Random Number Generator
     * @since 1.0.0
     *
     * @param non-negative-int $min [optional] <p>
     * Optional lowest value to be returned.
     * </p>
     * @param null|non-negative-int $max [optional] <p>
     * Optional highest value to be returned.
     * </p>
     *
     * @throws \FireHub\Core\Support\Exceptions\Random\NumberLessThenMinException If $min is less than 0.
     * @throws \FireHub\Core\Support\Exceptions\Random\MaxLessThenMinException If $max is less than $min.
     * @throws \FireHub\Core\Support\Exceptions\Random\NumberGreaterThenMaxException If $max is greater than
     * mt_getrandmax().
     *
     * @return non-negative-int A random integer value between min and max.
     */
    public static function number (int $min = 0, ?int $max = null):int {

        if ($min < 0)
            throw new NumberLessThenMinException()->withMin($min);

        if ($max < $min && $max !== null)
            throw new MaxLessThenMinException()
                ->withMin($min)
                ->withMax($max);

        if ($max > mt_getrandmax())
            throw new NumberGreaterThenMaxException()->withMax($max);

        return mt_rand($min, $max ?? mt_getrandmax());

    }

    /**
     * ### Get a cryptographically secure, uniformly selected integer
     *
     * The randomness generated by this function is suitable for all applications, including the generation of
     * long-term secrets, such as encryption keys.
     * @since 1.0.0
     *
     * @param int $min <p>
     * Optional lowest value to be returned.
     * </p>
     * @param int $max <p>
     * Optional highest value to be returned.
     * </p>
     *
     * @throws \FireHub\Core\Support\Exceptions\Random\MaxLessThenMinException If $max is less than $min.
     * @throws \FireHub\Core\Support\Exceptions\RandomException If an appropriate source of randomness cannot be found.
     *
     * @return int A cryptographically secure, uniformly selected integer from the closed interval [min, max].
     * Both min and max are possible return values.
     *
     * @caution This method is significantly slower than non-cryptographic random number generators like Random::number.
     */
    public static function secureNumber (int $min, int $max):int {

        if ($max < $min)
            throw new MaxLessThenMinException()
                ->withMin($min)
                ->withMax($max);

        try {

            return random_int($min, $max);

        } catch (InternalRandomException $e) {

            throw new RandomException()->withMessage($e->getMessage());

        }

    }

    /**
     * ### Get cryptographically secure random bytes
     *
     * Generates a string containing uniformly selected random bytes with the requested length.
     * As the returned bytes are selected completely randomly, the resulting string is likely to contain unprintable
     * characters or invalid UTF-8 sequences. It may be necessary to encode it before transmission or display.
     * The randomness generated by this function is suitable for all applications, including the generation of
     * long-term secrets, such as encryption keys.
     * @since 1.0.0
     *
     * @param positive-int $length <p>
     * The length of the random string that should be returned in bytes; must be 1 or greater.
     * </p>
     *
     * @throws \FireHub\Core\Support\Exceptions\Random\NumberLessThenMinException If length is less than 1.
     * @throws \FireHub\Core\Support\Exceptions\RandomException If an appropriate source of randomness cannot be found.
     *
     * @return non-empty-string A string containing the requested number of cryptographically secure random bytes.
     */
    public static function bytes (int $length):string {

        if ($length < 1)
            throw new NumberLessThenMinException()
                ->withMin($length);

        try {

            return random_bytes($length);

        } catch (InternalRandomException $e) {

            throw new RandomException()->withMessage($e->getMessage());

        }

    }

}